// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"database/sql"
	"github.com/rs/zerolog"
	"google.golang.org/grpc"
	"shopping/payment/internal/application/router/grpc"
	"shopping/payment/internal/infra/repo"
	"shopping/payment/internal/logging"
	"shopping/payment/internal/usecase"
)

// Injectors from wire.go:

func InitApp(tableName string, db *sql.DB, rpc *grpc.Server, logger zerolog.Logger, conn *grpc.ClientConn) error {
	paymentRepository := repo.NewPaymentRepository(tableName, db)
	orderRepository := router.NewOrderRepository(conn)
	serviceUsecase := usecase.NewService(paymentRepository, orderRepository)
	loggingUsecase := logging.LogApplicationAccess(serviceUsecase, logger)
	error2 := router.RegisterServer(loggingUsecase, rpc)
	return error2
}
