// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        (unknown)
// source: orderspb/events.proto

package orderspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderCreated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId string `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
}

func (x *OrderCreated) Reset() {
	*x = OrderCreated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderspb_events_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCreated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreated) ProtoMessage() {}

func (x *OrderCreated) ProtoReflect() protoreflect.Message {
	mi := &file_orderspb_events_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreated.ProtoReflect.Descriptor instead.
func (*OrderCreated) Descriptor() ([]byte, []int) {
	return file_orderspb_events_proto_rawDescGZIP(), []int{0}
}

func (x *OrderCreated) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderCreated) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

type OrderAddedItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Item *OrderAddedItem_Item `protobuf:"bytes,2,opt,name=item,proto3" json:"item,omitempty"`
}

func (x *OrderAddedItem) Reset() {
	*x = OrderAddedItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderspb_events_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderAddedItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAddedItem) ProtoMessage() {}

func (x *OrderAddedItem) ProtoReflect() protoreflect.Message {
	mi := &file_orderspb_events_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAddedItem.ProtoReflect.Descriptor instead.
func (*OrderAddedItem) Descriptor() ([]byte, []int) {
	return file_orderspb_events_proto_rawDescGZIP(), []int{1}
}

func (x *OrderAddedItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderAddedItem) GetItem() *OrderAddedItem_Item {
	if x != nil {
		return x.Item
	}
	return nil
}

type OrderCheckedOut struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CustomerId string  `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	Total      float64 `protobuf:"fixed64,3,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *OrderCheckedOut) Reset() {
	*x = OrderCheckedOut{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderspb_events_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCheckedOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCheckedOut) ProtoMessage() {}

func (x *OrderCheckedOut) ProtoReflect() protoreflect.Message {
	mi := &file_orderspb_events_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCheckedOut.ProtoReflect.Descriptor instead.
func (*OrderCheckedOut) Descriptor() ([]byte, []int) {
	return file_orderspb_events_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCheckedOut) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderCheckedOut) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *OrderCheckedOut) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type OrderReadied struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentId string `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
}

func (x *OrderReadied) Reset() {
	*x = OrderReadied{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderspb_events_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderReadied) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderReadied) ProtoMessage() {}

func (x *OrderReadied) ProtoReflect() protoreflect.Message {
	mi := &file_orderspb_events_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderReadied.ProtoReflect.Descriptor instead.
func (*OrderReadied) Descriptor() ([]byte, []int) {
	return file_orderspb_events_proto_rawDescGZIP(), []int{3}
}

func (x *OrderReadied) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderReadied) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type OrderCanceled struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PaymentId string `protobuf:"bytes,2,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
}

func (x *OrderCanceled) Reset() {
	*x = OrderCanceled{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderspb_events_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCanceled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCanceled) ProtoMessage() {}

func (x *OrderCanceled) ProtoReflect() protoreflect.Message {
	mi := &file_orderspb_events_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCanceled.ProtoReflect.Descriptor instead.
func (*OrderCanceled) Descriptor() ([]byte, []int) {
	return file_orderspb_events_proto_rawDescGZIP(), []int{4}
}

func (x *OrderCanceled) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *OrderCanceled) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type OrderCompleted struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *OrderCompleted) Reset() {
	*x = OrderCompleted{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderspb_events_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderCompleted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCompleted) ProtoMessage() {}

func (x *OrderCompleted) ProtoReflect() protoreflect.Message {
	mi := &file_orderspb_events_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCompleted.ProtoReflect.Descriptor instead.
func (*OrderCompleted) Descriptor() ([]byte, []int) {
	return file_orderspb_events_proto_rawDescGZIP(), []int{5}
}

func (x *OrderCompleted) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type OrderAddedItem_Item struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ProductId string  `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	Price     float64 `protobuf:"fixed64,2,opt,name=price,proto3" json:"price,omitempty"`
	Quantity  int32   `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
}

func (x *OrderAddedItem_Item) Reset() {
	*x = OrderAddedItem_Item{}
	if protoimpl.UnsafeEnabled {
		mi := &file_orderspb_events_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OrderAddedItem_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAddedItem_Item) ProtoMessage() {}

func (x *OrderAddedItem_Item) ProtoReflect() protoreflect.Message {
	mi := &file_orderspb_events_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAddedItem_Item.ProtoReflect.Descriptor instead.
func (*OrderAddedItem_Item) Descriptor() ([]byte, []int) {
	return file_orderspb_events_proto_rawDescGZIP(), []int{1, 0}
}

func (x *OrderAddedItem_Item) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *OrderAddedItem_Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *OrderAddedItem_Item) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

var File_orderspb_events_proto protoreflect.FileDescriptor

var file_orderspb_events_proto_rawDesc = []byte{
	0x0a, 0x15, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x73, 0x70, 0x62, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x70, 0x62,
	0x22, 0x3f, 0x0a, 0x0c, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x49,
	0x64, 0x22, 0xab, 0x01, 0x0a, 0x0e, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x41, 0x64, 0x64, 0x65, 0x64,
	0x49, 0x74, 0x65, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x70, 0x62, 0x2e, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x41, 0x64, 0x64, 0x65, 0x64, 0x49, 0x74, 0x65, 0x6d, 0x2e, 0x49, 0x74, 0x65, 0x6d,
	0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x1a, 0x57, 0x0a, 0x04, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x71, 0x75, 0x61, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x22,
	0x58, 0x0a, 0x0f, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x65, 0x64, 0x4f,
	0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x65,
	0x72, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x3d, 0x0a, 0x0c, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x52, 0x65, 0x61, 0x64, 0x69, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x0d, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x79,
	0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70,
	0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x0e, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x42, 0x72, 0x0a, 0x0b, 0x63, 0x6f,
	0x6d, 0x2e, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x70, 0x62, 0x42, 0x0b, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1a, 0x73, 0x68, 0x6f, 0x70, 0x70, 0x69,
	0x6e, 0x67, 0x2f, 0x6f, 0x72, 0x64, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x72, 0x64, 0x65,
	0x72, 0x73, 0x70, 0x62, 0xa2, 0x02, 0x03, 0x4f, 0x58, 0x58, 0xaa, 0x02, 0x07, 0x4f, 0x72, 0x64,
	0x65, 0x72, 0x70, 0x62, 0xca, 0x02, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x70, 0x62, 0xe2, 0x02,
	0x13, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x70, 0x62, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_orderspb_events_proto_rawDescOnce sync.Once
	file_orderspb_events_proto_rawDescData = file_orderspb_events_proto_rawDesc
)

func file_orderspb_events_proto_rawDescGZIP() []byte {
	file_orderspb_events_proto_rawDescOnce.Do(func() {
		file_orderspb_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_orderspb_events_proto_rawDescData)
	})
	return file_orderspb_events_proto_rawDescData
}

var file_orderspb_events_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_orderspb_events_proto_goTypes = []interface{}{
	(*OrderCreated)(nil),        // 0: orderpb.OrderCreated
	(*OrderAddedItem)(nil),      // 1: orderpb.OrderAddedItem
	(*OrderCheckedOut)(nil),     // 2: orderpb.OrderCheckedOut
	(*OrderReadied)(nil),        // 3: orderpb.OrderReadied
	(*OrderCanceled)(nil),       // 4: orderpb.OrderCanceled
	(*OrderCompleted)(nil),      // 5: orderpb.OrderCompleted
	(*OrderAddedItem_Item)(nil), // 6: orderpb.OrderAddedItem.Item
}
var file_orderspb_events_proto_depIdxs = []int32{
	6, // 0: orderpb.OrderAddedItem.item:type_name -> orderpb.OrderAddedItem.Item
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_orderspb_events_proto_init() }
func file_orderspb_events_proto_init() {
	if File_orderspb_events_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_orderspb_events_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCreated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderspb_events_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderAddedItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderspb_events_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCheckedOut); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderspb_events_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderReadied); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderspb_events_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCanceled); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderspb_events_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderCompleted); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_orderspb_events_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OrderAddedItem_Item); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_orderspb_events_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_orderspb_events_proto_goTypes,
		DependencyIndexes: file_orderspb_events_proto_depIdxs,
		MessageInfos:      file_orderspb_events_proto_msgTypes,
	}.Build()
	File_orderspb_events_proto = out.File
	file_orderspb_events_proto_rawDesc = nil
	file_orderspb_events_proto_goTypes = nil
	file_orderspb_events_proto_depIdxs = nil
}
