version: "3.8"

services:
  # monolith:
  #   container_name: monolith
  #   hostname: monolith
  #   build:
  #     context: .
  #     dockerfile: docker/Dockerfile
  #   ports:
  #     - '8080:8080'
  #     - '8085:8085'
  #   env_file:
  #     - docker/.env
  #   depends_on:
  #     - postgres
  postgres:
    container_name: postgres
    hostname: postgres
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data'
      - './docker/database:/docker-entrypoint-initdb.d'
  pgAdmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=giangle2198@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=1
    links: 
      - postgres:postgres
    ports:
      - 83:80
    container_name: pg_admin 
  nats:
    container_name: nats
    hostname: nats
    image: nats:2.9-alpine
    ports:
      - 4222:4222
      - 8222:8222
    command:
      - -c 
      - config/config_nats.conf
    volumes:
      - 'jsdata:/var/lib/nats/data'
      - './docker/config_nats.conf:/config/config_nats.conf'
  # nats-ui:
  #   container_name: nats-ui
  #   hostname: nats-ui
  #   image: piotrpersona/nats-streaming-ui
  #   ports:
  #     - '8282:8282'
  #   links: 
  #     - nats:nats
  #   environment:
  #     - STAN_URL=nats:4222
  #     - STAN_MONITOR_URL=http://nats:8222
  #     - STAN_CLUSTER=test-cluster
volumes:
  pgdata:
  jsdata:
