// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"database/sql"
	"github.com/rs/zerolog"
	"google.golang.org/grpc"
	"shopping/order/internal/application/router/grpc"
	"shopping/order/internal/infra/repo"
	"shopping/order/internal/logging"
	"shopping/order/internal/usecase"
)

// Injectors from wire.go:

func InitApp(tableName string, db *sql.DB, rpc *grpc.Server, logger zerolog.Logger, conn *grpc.ClientConn) error {
	orderRepository := repo.NewOrderRepository(tableName, db)
	paymentRepository := router.NewPaymentRepository(conn)
	customerRepository := router.NewCustomerRepository(conn)
	productRepository := router.NewProductRepository(conn)
	serviceUsecase := usecase.NewService(orderRepository, paymentRepository, customerRepository, productRepository)
	loggingUsecase := logging.LogApplicationAccess(serviceUsecase, logger)
	error2 := router.RegisterServer(loggingUsecase, rpc)
	return error2
}
