// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package application

import (
	"database/sql"
	"github.com/rs/zerolog"
	"google.golang.org/grpc"
	"shopping/product/internal/application/router/grpc"
	"shopping/product/internal/infra/repo"
	"shopping/product/internal/logging"
	"shopping/product/internal/usecase"
)

// Injectors from wire.go:

func InitApp(tableName string, db *sql.DB, rpc *grpc.Server, logger zerolog.Logger) error {
	productRepository := repo.NewProductRepository(tableName, db)
	serviceUsecase := usecase.NewService(productRepository)
	loggingUsecase := logging.LogApplicationAccess(serviceUsecase, logger)
	error2 := router.RegisterServer(loggingUsecase, rpc)
	return error2
}
